import { getAuthenticatedClient } from "@features/auth/hooks/authClient";
import { workspaceApi } from "@features/workspace/hooks/useWorkspace";
import { useNavigationStore } from "@stores/navigationStore";
import { useCallback, useState } from "react";
import { toast } from "sonner";

/**
 * Opens the task generated by a scheduled task's most recent run inside the
 * Work view. Scheduled tasks always run in cloud mode and aren't repo-scoped,
 * so we bypass the standard TaskCreationSaga (which would try to clone the
 * sentinel repository) and just ensure a cloud-only workspace exists before
 * navigating to the in-Work task-detail view.
 */
export function useOpenLastRun() {
  const [isOpening, setIsOpening] = useState(false);
  const navigateToWorkTask = useNavigationStore((s) => s.navigateToWorkTask);

  const openLastRun = useCallback(
    async (taskId: string, taskRunId?: string | null) => {
      setIsOpening(true);
      try {
        const posthogClient = await getAuthenticatedClient();
        if (!posthogClient) {
          toast.error("Couldn't open the last run: not authenticated");
          return;
        }

        // Surface task/run fetch errors early. WorkTaskDetailView reads the
        // task fresh from the tasks cache.
        await posthogClient.getTask(taskId);
        if (taskRunId) {
          await posthogClient.getTaskRun(taskId, taskRunId);
        }

        const existing = await workspaceApi.get(taskId);
        if (!existing) {
          await workspaceApi.create({
            taskId,
            mainRepoPath: "",
            folderId: "",
            folderPath: "",
            mode: "cloud",
          });
        }

        navigateToWorkTask(taskId);
      } catch (error) {
        toast.error(
          error instanceof Error ? error.message : "Couldn't open the last run",
        );
      } finally {
        setIsOpening(false);
      }
    },
    [navigateToWorkTask],
  );

  return { openLastRun, isOpening };
}
