import { getAuthenticatedClient } from "@features/auth/hooks/authClient";
import { workspaceApi } from "@features/workspace/hooks/useWorkspace";
import type { Task } from "@shared/types";
import { useNavigationStore } from "@stores/navigationStore";
import { useCallback, useState } from "react";
import { toast } from "sonner";

/**
 * Opens the task generated by a scheduled task's most recent run inside the
 * Work view. Scheduled tasks always run in cloud mode and aren't repo-scoped,
 * so we bypass the standard TaskCreationSaga (which would try to clone the
 * sentinel repository) and just ensure a cloud-only workspace exists.
 */
export function useOpenLastRun() {
  const [isOpening, setIsOpening] = useState(false);
  const navigateToWorkTaskDetail = useNavigationStore(
    (s) => s.navigateToWorkTaskDetail,
  );

  const openLastRun = useCallback(
    async (taskId: string, taskRunId?: string | null) => {
      setIsOpening(true);
      try {
        const posthogClient = await getAuthenticatedClient();
        if (!posthogClient) {
          toast.error("Couldn't open the last run: not authenticated");
          return;
        }

        const task = (await posthogClient.getTask(taskId)) as unknown as Task;
        if (taskRunId) {
          const run = await posthogClient.getTaskRun(taskId, taskRunId);
          task.latest_run = run;
        }

        const existing = await workspaceApi.get(taskId);
        if (!existing) {
          await workspaceApi.create({
            taskId,
            mainRepoPath: "",
            folderId: "",
            folderPath: "",
            mode: "cloud",
          });
        }

        navigateToWorkTaskDetail(task);
      } catch (error) {
        toast.error(
          error instanceof Error ? error.message : "Couldn't open the last run",
        );
      } finally {
        setIsOpening(false);
      }
    },
    [navigateToWorkTaskDetail],
  );

  return { openLastRun, isOpening };
}
