import type { TaskService } from "@features/task-detail/service/service";
import { get } from "@renderer/di/container";
import { RENDERER_TOKENS } from "@renderer/di/tokens";
import { useNavigationStore } from "@stores/navigationStore";
import { useCallback, useState } from "react";
import { toast } from "sonner";

/**
 * Opens the task generated by a scheduled task's most recent run: switches
 * the app to Code mode and navigates to that task's detail view. Reuses the
 * same TaskService.openTask path the deep-link handler uses, so workspace
 * setup is taken care of.
 */
export function useOpenLastRun() {
  const [isOpening, setIsOpening] = useState(false);
  const setMode = useNavigationStore((s) => s.setMode);
  const navigateToTask = useNavigationStore((s) => s.navigateToTask);

  const openLastRun = useCallback(
    async (taskId: string, taskRunId?: string | null) => {
      setIsOpening(true);
      try {
        const taskService = get<TaskService>(RENDERER_TOKENS.TaskService);
        const result = await taskService.openTask(
          taskId,
          taskRunId ?? undefined,
        );
        if (!result.success) {
          toast.error(`Couldn't open the last run: ${result.error}`);
          return;
        }
        setMode("code");
        navigateToTask(result.data.task);
      } catch (error) {
        toast.error(
          error instanceof Error ? error.message : "Couldn't open the last run",
        );
      } finally {
        setIsOpening(false);
      }
    },
    [setMode, navigateToTask],
  );

  return { openLastRun, isOpening };
}
