import type { Spec } from "@json-render/react";
import type {
  DashboardRecord,
  DashboardSummary,
} from "@posthog/core/canvas/dashboardSchemas";
import { useHostTRPC } from "@posthog/host-router/react";
import { useDashboardEditStore } from "@posthog/ui/features/canvas/stores/dashboardEditStore";
import { toast } from "@posthog/ui/primitives/toast";
import { logger } from "@posthog/ui/shell/logger";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { useCallback } from "react";

const log = logger.scope("dashboards");

/** Saved dashboards for a channel (file-backed, generated by json-render). */
export function useDashboards(channelId: string | undefined): {
  dashboards: DashboardSummary[];
  isLoading: boolean;
} {
  const trpc = useHostTRPC();
  const { data, isLoading } = useQuery(
    trpc.dashboards.list.queryOptions(
      { channelId: channelId ?? "" },
      { enabled: !!channelId, staleTime: 5_000 },
    ),
  );
  return { dashboards: data ?? [], isLoading };
}

/** A single saved dashboard record (spec + metadata). */
export function useDashboard(id: string | undefined): {
  dashboard: DashboardRecord | null | undefined;
  isLoading: boolean;
  isFetching: boolean;
} {
  const trpc = useHostTRPC();
  const { data, isLoading, isFetching } = useQuery(
    trpc.dashboards.get.queryOptions(
      { id: id ?? "" },
      { enabled: !!id, staleTime: 5_000 },
    ),
  );
  return { dashboard: data, isLoading, isFetching };
}

/** Save (update) + fork (create) mutations, invalidating the list + record. */
export function useDashboardMutations() {
  const trpc = useHostTRPC();
  const queryClient = useQueryClient();

  const invalidate = () => {
    void queryClient.invalidateQueries(trpc.dashboards.list.pathFilter());
    void queryClient.invalidateQueries(trpc.dashboards.get.pathFilter());
  };

  const save = useMutation(
    trpc.dashboards.update.mutationOptions({ onSuccess: invalidate }),
  );
  const create = useMutation(
    trpc.dashboards.create.mutationOptions({ onSuccess: invalidate }),
  );
  const remove = useMutation(
    trpc.dashboards.delete.mutationOptions({ onSuccess: invalidate }),
  );

  return {
    saveDashboard: (id: string, spec: Spec | null, name?: string) =>
      save.mutateAsync({
        id,
        spec: spec as Record<string, unknown> | null,
        name,
      }),
    createDashboard: (channelId: string, name: string, spec: Spec | null) =>
      create.mutateAsync({
        channelId,
        name,
        spec: spec as Record<string, unknown> | null,
      }),
    deleteDashboard: (id: string) => remove.mutateAsync({ id }),
    isSaving: save.isPending,
    isCreating: create.isPending,
    isDeleting: remove.isPending,
  };
}

/** Create a blank dashboard in a channel, enter edit mode, and navigate to it. */
export function useCreateAndOpenDashboard(
  channelId: string | undefined,
): (name?: string) => Promise<void> {
  const navigate = useNavigate();
  const { createDashboard } = useDashboardMutations();
  const setEditing = useDashboardEditStore((s) => s.setEditing);

  return useCallback(
    async (name = "Untitled dashboard") => {
      if (!channelId) return;
      try {
        const record = await createDashboard(channelId, name, null);
        setEditing(record.id, true);
        await navigate({
          to: "/website/$channelId/dashboards/$dashboardId",
          params: { channelId, dashboardId: record.id },
        });
      } catch (error) {
        log.error("Failed to create dashboard", { error });
        toast.error("Couldn't create dashboard", {
          description: error instanceof Error ? error.message : String(error),
        });
      }
    },
    [channelId, createDashboard, navigate, setEditing],
  );
}
