import { useHostTRPC } from "@posthog/host-router/react";
import type { Channel } from "@posthog/ui/features/canvas/hooks/useChannels";
import { useQueries } from "@tanstack/react-query";
import { useMemo } from "react";

/** A canvas generated by a task, with enough to navigate to it. */
export interface CanvasArtifact {
  id: string;
  channelId: string;
  name: string;
}

/**
 * Map of taskId → the canvases that task generated. A freeform canvas records
 * its generating task in `generationTaskId` (never cleared), so this is the
 * durable task → canvas link. Fans out one `dashboards.list` query per channel
 * (the list endpoint is channel-scoped); results are shared with the channel
 * sidebar's per-channel queries through the react-query cache.
 */
export function useTaskCanvasArtifacts(
  channels: Channel[],
): Map<string, CanvasArtifact[]> {
  const trpc = useHostTRPC();
  const results = useQueries({
    queries: channels.map((channel) =>
      trpc.dashboards.list.queryOptions(
        { channelId: channel.id },
        { staleTime: 5_000 },
      ),
    ),
  });
  return useMemo(() => {
    const map = new Map<string, CanvasArtifact[]>();
    for (const res of results) {
      for (const dashboard of res.data ?? []) {
        if (!dashboard.generationTaskId) continue;
        const list = map.get(dashboard.generationTaskId) ?? [];
        list.push({
          id: dashboard.id,
          channelId: dashboard.channelId,
          name: dashboard.name,
        });
        map.set(dashboard.generationTaskId, list);
      }
    }
    return map;
  }, [results]);
}
