/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as McpServersRouteImport } from './routes/mcp-servers'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as CodeIndexRouteImport } from './routes/code/index'
import { Route as SettingsCategoryRouteImport } from './routes/settings/$category'
import { Route as FoldersFolderIdRouteImport } from './routes/folders/$folderId'
import { Route as CodeInboxRouteImport } from './routes/code/inbox'
import { Route as CodeArchivedRouteImport } from './routes/code/archived'
import { Route as CodeTasksTaskIdRouteImport } from './routes/code/tasks/$taskId'
import { Route as CodeTasksPendingKeyRouteImport } from './routes/code/tasks/pending.$key'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const McpServersRoute = McpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeIndexRoute = CodeIndexRouteImport.update({
  id: '/code/',
  path: '/code/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoryRoute = SettingsCategoryRouteImport.update({
  id: '/settings/$category',
  path: '/settings/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeInboxRoute = CodeInboxRouteImport.update({
  id: '/code/inbox',
  path: '/code/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeArchivedRoute = CodeArchivedRouteImport.update({
  id: '/code/archived',
  path: '/code/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeTasksTaskIdRoute = CodeTasksTaskIdRouteImport.update({
  id: '/code/tasks/$taskId',
  path: '/code/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeTasksPendingKeyRoute = CodeTasksPendingKeyRouteImport.update({
  id: '/code/tasks/pending/$key',
  path: '/code/tasks/pending/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/inbox': typeof InboxRoute
  '/mcp-servers': typeof McpServersRoute
  '/skills': typeof SkillsRoute
  '/website': typeof WebsiteRoute
  '/code/archived': typeof CodeArchivedRoute
  '/code/inbox': typeof CodeInboxRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/settings/$category': typeof SettingsCategoryRoute
  '/code/': typeof CodeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/code/tasks/$taskId': typeof CodeTasksTaskIdRoute
  '/code/tasks/pending/$key': typeof CodeTasksPendingKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/inbox': typeof InboxRoute
  '/mcp-servers': typeof McpServersRoute
  '/skills': typeof SkillsRoute
  '/website': typeof WebsiteRoute
  '/code/archived': typeof CodeArchivedRoute
  '/code/inbox': typeof CodeInboxRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/settings/$category': typeof SettingsCategoryRoute
  '/code': typeof CodeIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/code/tasks/$taskId': typeof CodeTasksTaskIdRoute
  '/code/tasks/pending/$key': typeof CodeTasksPendingKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/inbox': typeof InboxRoute
  '/mcp-servers': typeof McpServersRoute
  '/skills': typeof SkillsRoute
  '/website': typeof WebsiteRoute
  '/code/archived': typeof CodeArchivedRoute
  '/code/inbox': typeof CodeInboxRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/settings/$category': typeof SettingsCategoryRoute
  '/code/': typeof CodeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/code/tasks/$taskId': typeof CodeTasksTaskIdRoute
  '/code/tasks/pending/$key': typeof CodeTasksPendingKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command-center'
    | '/inbox'
    | '/mcp-servers'
    | '/skills'
    | '/website'
    | '/code/archived'
    | '/code/inbox'
    | '/folders/$folderId'
    | '/settings/$category'
    | '/code/'
    | '/settings/'
    | '/code/tasks/$taskId'
    | '/code/tasks/pending/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command-center'
    | '/inbox'
    | '/mcp-servers'
    | '/skills'
    | '/website'
    | '/code/archived'
    | '/code/inbox'
    | '/folders/$folderId'
    | '/settings/$category'
    | '/code'
    | '/settings'
    | '/code/tasks/$taskId'
    | '/code/tasks/pending/$key'
  id:
    | '__root__'
    | '/'
    | '/command-center'
    | '/inbox'
    | '/mcp-servers'
    | '/skills'
    | '/website'
    | '/code/archived'
    | '/code/inbox'
    | '/folders/$folderId'
    | '/settings/$category'
    | '/code/'
    | '/settings/'
    | '/code/tasks/$taskId'
    | '/code/tasks/pending/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandCenterRoute: typeof CommandCenterRoute
  InboxRoute: typeof InboxRoute
  McpServersRoute: typeof McpServersRoute
  SkillsRoute: typeof SkillsRoute
  WebsiteRoute: typeof WebsiteRoute
  CodeArchivedRoute: typeof CodeArchivedRoute
  CodeInboxRoute: typeof CodeInboxRoute
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  SettingsCategoryRoute: typeof SettingsCategoryRoute
  CodeIndexRoute: typeof CodeIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  CodeTasksTaskIdRoute: typeof CodeTasksTaskIdRoute
  CodeTasksPendingKeyRoute: typeof CodeTasksPendingKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-servers': {
      id: '/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/mcp-servers'
      preLoaderRoute: typeof McpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/': {
      id: '/code/'
      path: '/code'
      fullPath: '/code/'
      preLoaderRoute: typeof CodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$category': {
      id: '/settings/$category'
      path: '/settings/$category'
      fullPath: '/settings/$category'
      preLoaderRoute: typeof SettingsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/inbox': {
      id: '/code/inbox'
      path: '/code/inbox'
      fullPath: '/code/inbox'
      preLoaderRoute: typeof CodeInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/archived': {
      id: '/code/archived'
      path: '/code/archived'
      fullPath: '/code/archived'
      preLoaderRoute: typeof CodeArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/tasks/$taskId': {
      id: '/code/tasks/$taskId'
      path: '/code/tasks/$taskId'
      fullPath: '/code/tasks/$taskId'
      preLoaderRoute: typeof CodeTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/tasks/pending/$key': {
      id: '/code/tasks/pending/$key'
      path: '/code/tasks/pending/$key'
      fullPath: '/code/tasks/pending/$key'
      preLoaderRoute: typeof CodeTasksPendingKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandCenterRoute: CommandCenterRoute,
  InboxRoute: InboxRoute,
  McpServersRoute: McpServersRoute,
  SkillsRoute: SkillsRoute,
  WebsiteRoute: WebsiteRoute,
  CodeArchivedRoute: CodeArchivedRoute,
  CodeInboxRoute: CodeInboxRoute,
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  SettingsCategoryRoute: SettingsCategoryRoute,
  CodeIndexRoute: CodeIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CodeTasksTaskIdRoute: CodeTasksTaskIdRoute,
  CodeTasksPendingKeyRoute: CodeTasksPendingKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
