export type HogletGender = "male" | "female";

interface NameEntry {
  name: string;
  gender: HogletGender;
}

const ENTRIES: readonly NameEntry[] = [
  { name: "James", gender: "male" },
  { name: "Tim", gender: "male" },
  { name: "Marius", gender: "male" },
  { name: "Eric", gender: "male" },
  { name: "Lottie", gender: "female" },
  { name: "Michael", gender: "male" },
  { name: "Charles", gender: "male" },
  { name: "Cory", gender: "male" },
  { name: "Joe", gender: "male" },
  { name: "Eli", gender: "male" },
  { name: "Paul", gender: "male" },
  { name: "Simon", gender: "male" },
  { name: "Andy", gender: "male" },
  { name: "Coua", gender: "female" },
  { name: "Ben", gender: "male" },
  { name: "Annika", gender: "female" },
  { name: "Ian", gender: "male" },
  { name: "Kendal", gender: "female" },
  { name: "Daniel", gender: "male" },
  { name: "Raquel", gender: "female" },
  { name: "Thomas", gender: "male" },
  { name: "Frank", gender: "male" },
  { name: "Tomas", gender: "male" },
  { name: "Marcus", gender: "male" },
  { name: "Robbie", gender: "male" },
  { name: "Manoel", gender: "male" },
  { name: "Tom", gender: "male" },
  { name: "Juraj", gender: "male" },
  { name: "Julian", gender: "male" },
  { name: "Fraser", gender: "male" },
  { name: "Mine", gender: "female" },
  { name: "Steven", gender: "male" },
  { name: "Sandy", gender: "male" },
  { name: "Dylan", gender: "male" },
  { name: "Seb", gender: "male" },
  { name: "Georgiy", gender: "male" },
  { name: "Leon", gender: "male" },
  { name: "Olly", gender: "male" },
  { name: "Anna", gender: "female" },
  { name: "Abigail", gender: "female" },
  { name: "Bryan", gender: "male" },
  { name: "Patricio", gender: "male" },
  { name: "Ioannis", gender: "male" },
  { name: "Danilo", gender: "male" },
  { name: "Ross", gender: "male" },
  { name: "Scott", gender: "male" },
  { name: "Rafael", gender: "male" },
  { name: "Adam", gender: "male" },
  { name: "Anders", gender: "male" },
  { name: "Peter", gender: "male" },
  { name: "Pawel", gender: "male" },
  { name: "Lucas", gender: "male" },
  { name: "Meikel", gender: "male" },
  { name: "Aleks", gender: "male" },
  { name: "Phil", gender: "male" },
  { name: "Joshua", gender: "male" },
  { name: "Sean", gender: "male" },
  { name: "Dana", gender: "female" },
  { name: "Magda", gender: "female" },
  { name: "Brian", gender: "male" },
  { name: "Hugues", gender: "male" },
  { name: "Rodrigo", gender: "male" },
  { name: "Luke", gender: "male" },
  { name: "Julia", gender: "female" },
  { name: "Alex", gender: "male" },
  { name: "Landon", gender: "male" },
  { name: "Chris", gender: "male" },
  { name: "Nick", gender: "male" },
  { name: "Hector", gender: "male" },
  { name: "Javier", gender: "male" },
  { name: "Sachin", gender: "male" },
  { name: "Edwin", gender: "male" },
  { name: "Kaya", gender: "female" },
  { name: "Jose", gender: "male" },
  { name: "Tyler", gender: "male" },
  { name: "Abe", gender: "male" },
  { name: "Vincent", gender: "male" },
  { name: "Yasen", gender: "male" },
  { name: "Janani", gender: "female" },
  { name: "Arthur", gender: "male" },
  { name: "Tara", gender: "female" },
  { name: "Alessandro", gender: "male" },
  { name: "Jonathan", gender: "male" },
  { name: "Jon", gender: "male" },
  { name: "Kyle", gender: "male" },
  { name: "Radu", gender: "male" },
  { name: "Rune", gender: "male" },
  { name: "Christian", gender: "male" },
  { name: "Jordo", gender: "male" },
  { name: "Tue", gender: "male" },
  { name: "Mark", gender: "male" },
  { name: "Carol", gender: "female" },
  { name: "Eleftheria", gender: "female" },
  { name: "Ryan", gender: "male" },
  { name: "Carlos", gender: "male" },
  { name: "Jovan", gender: "male" },
  { name: "Georgis", gender: "male" },
  { name: "Aleksander", gender: "male" },
  { name: "Christophe", gender: "male" },
  { name: "Dustin", gender: "male" },
  { name: "Gustavo", gender: "male" },
  { name: "Natalia", gender: "female" },
  { name: "Marce", gender: "male" },
  { name: "Zbynek", gender: "male" },
  { name: "Judy", gender: "female" },
  { name: "Sven", gender: "male" },
  { name: "Cleo", gender: "female" },
  { name: "Sara", gender: "female" },
  { name: "Andrew", gender: "male" },
  { name: "Kim", gender: "female" },
  { name: "Matt", gender: "male" },
  { name: "Rory", gender: "male" },
  { name: "Catherine", gender: "female" },
  { name: "Vasco", gender: "male" },
  { name: "Jordan", gender: "male" },
  { name: "Sarah", gender: "female" },
  { name: "Bill", gender: "male" },
  { name: "Jina", gender: "female" },
  { name: "Leo", gender: "male" },
  { name: "Estefania", gender: "female" },
  { name: "Reece", gender: "male" },
  { name: "Hayne", gender: "male" },
  { name: "Anna-Marie", gender: "female" },
  { name: "Heidi", gender: "female" },
  { name: "Richard", gender: "male" },
  { name: "Ahmed", gender: "male" },
  { name: "George", gender: "male" },
  { name: "Marcel", gender: "male" },
  { name: "Abhischek", gender: "male" },
  { name: "Christiaan", gender: "male" },
  { name: "Matheus", gender: "male" },
  { name: "Jakob", gender: "male" },
  { name: "Andre", gender: "male" },
  { name: "Sam", gender: "male" },
  { name: "Zachary", gender: "male" },
  { name: "Kliment", gender: "male" },
  { name: "Fernando", gender: "male" },
  { name: "Adlet", gender: "female" },
  { name: "Phillip", gender: "male" },
  { name: "Mike", gender: "male" },
  { name: "Eliana", gender: "female" },
  { name: "Georges", gender: "male" },
  { name: "Lorena", gender: "female" },
  { name: "Will", gender: "male" },
  { name: "Vojta", gender: "male" },
  { name: "Xander", gender: "male" },
  { name: "Catalin", gender: "female" },
  { name: "Raul", gender: "male" },
  { name: "Nicholas", gender: "male" },
  { name: "Jonah", gender: "male" },
  { name: "Lizzie", gender: "female" },
  { name: "Stephen", gender: "male" },
  { name: "Tommy", gender: "male" },
  { name: "Jake", gender: "male" },
  { name: "Brandon", gender: "male" },
  { name: "Felipe", gender: "male" },
  { name: "Dennis", gender: "male" },
  { name: "Aly", gender: "female" },
  { name: "Keelan", gender: "male" },
  { name: "Ruby", gender: "female" },
  { name: "Arnaud", gender: "male" },
  { name: "Liam", gender: "male" },
];

export const HOGLET_NAMES = ENTRIES.map((e) => e.name);

export type HogletName = string;

const GENDER_MAP = new Map<string, HogletGender>(
  ENTRIES.map((e) => [e.name, e.gender]),
);

export function genderForName(name: string | null): HogletGender {
  if (!name) return "male";
  return GENDER_MAP.get(name) ?? "male";
}
